# syntax=docker/dockerfile:experimental

FROM golang:1.22-alpine AS builder
RUN apk add -U --no-cache \
    build-base \
    ca-certificates \
    git \
    sqlite \
    taglib-dev \
    zlib-dev
WORKDIR /src
COPY . .
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    GOOS=linux go build -o musiqlx cmd/musiqlx/musiqlx.go

FROM alpine:3.18
RUN apk add -U --no-cache \
    ffmpeg \
    mpv \
    ca-certificates \
    shared-mime-info
COPY --from=builder \
    /usr/lib/libgcc_s.so.1 \
    /usr/lib/libstdc++.so.6 \
    /usr/lib/libtag.so.1 \
    /usr/lib/
COPY --from=builder \
    /src/musiqlx \
    /bin/
VOLUME ["/cache", "/data", "/music", "/podcasts"]
EXPOSE 80
ENV MUSIQLX_DB_PATH /data/musiqlx.db
ENV MUSIQLX_LISTEN_ADDR :80
ENV MUSIQLX_MUSIC_PATH /music
ENV MUSIQLX_PODCAST_PATH /podcasts
ENV MUSIQLX_PLAYLISTS_PATH /playlists
ENV MUSIQLX_CACHE_PATH /cache
CMD ["musiqlx"]
